# Generated by Django 4.2 on 2023-07-08 21:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0002_alter_stock_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
